version: '3'

services:
  excel-api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
    restart: unless-stopped
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/excel_db
    networks:
      - excel-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped
    environment:
      - MONGO_INITDB_DATABASE=excel_db
    networks:
      - excel-network

volumes:
  mongodb_data:

networks:
  excel-network:
    driver: bridge